### ISSUE TITLE
Rephrase side menu entries and remove subheadings.

### ISSUE THREAD

**Issue by that-andrew** [Taaqif/ionic-talkable#2]
**Client Issue ID:** 000003
**Date Received:** 22/08/2017 
**Issue:** 
No need for subheadings in the menu.
Change "Overview" to "Entire Program"
Example:
![menu-simpler](https://user-images.githubusercontent.com/24713676/29597623-773b3114-87f6-11e7-9204-9a0ea6367df5.jpg)

**Comment by Taaqif** [comment]
Fixed in latest commit
