### ISSUE TITLE
Week Bottom navigation heading text is being clipped

### ISSUE THREAD

**Issue by that-andrew** [Taaqif/ionic-talkable#3]
**Client Issue ID:** 000002
**Date Received:** 22/08/2017
**Issue:**
Key Word Sign text disappears when selected
**Notes**
Unable to replicate on any of my testing devices.
![screenshot_2017-08-21-18-54-10](https://user-images.githubusercontent.com/24713676/29597735-2ba51ffc-87f7-11e7-8a1b-736d17e3b9b8.png)

**Comment by Taaqif** [comment]
Changed 'key word signs' to 'key words'

**Comment by that-andrew** [comment]
was thinking it would probably just be a scaling issue on certain resolutions. I couldn't replicate it on any of my own devices.
for the sake of consistency it needs to remain "Key Word Signs" as that's how it appears everywhere else in the app. my fault, I should have explained it further.
