### ISSUE TITLE
Weekly content swipe between tabs not present

### ISSUE THREAD

**Issue by that-andrew** [Taaqif/ionic-talkable#4]
**Client Issue ID:** 000004
**Date Received:** 22/08/2017
**Issue:**
Swiping between tabs within each week isn't present.
**Expected Behavior:**
Swiping gesture (left to right or right to left) should navigate to the tab in the opposite direction of the gesture. (Standard inverse left/right touch screen navigation behavior)
**Current Behavior:**
Screens do not respond to left/right swipe gestures

**Comment by Taaqif** [comment]
Ionic does not provide a module that does this. I tried using the 'super tabs' module but that didn't work when I tried. Someone else can look into it. At present o doubt think this is an issue
