### ISSUE TITLE
Android system Back button exits entire app

### ISSUE THREAD

**Issue by that-andrew** [Taaqif/ionic-talkable#5]
**Client Issue ID:** 000006
**Date Received:** 22/08/2017
**Issue:**
Android system Back button exits entire app
**Expected Behavior:**
When the user presses the 'back' button on the on-screen navigation bar or physical hardware 'back' button the app will return the user to the previous (or most appropriate) screen or home screen.
**Current Behavior:**
When the user presses the 'back' button on the on-screen navigation bar or physical hardware 'back' button the app exits completely regardless of which screen the user is on.

**Comment by Taaqif** [comment]
Will implement a way of returning to the home screen AKA the current week they are on. If they are on the current week, the app will exit. 
Is this acceptable behaviour for the app?
